server:
  port: 9090
spring:
  application:
    name: ORGANIZATION-SERVICE

    graphql:
      graphiql:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/organization
    username: root
    password: 123
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0

